#!/usr/bin/env python3
"""Generate src/data/servers.sql from src/data/servers.json for D1 import.

The output file contains:
  - DROP/CREATE schema
  - Multi-row INSERT statements (batched 500 per statement) for all servers
  - CREATE INDEX

Run with `npm run export-d1`. Upload with `npm run upload-d1`.

This script does NOT need sqlite3 or any other dependency beyond json.
"""
from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SERVERS_JSON = PROJECT_ROOT / "src" / "data" / "servers.json"
OUT_SQL = PROJECT_ROOT / "src" / "data" / "servers.sql"

# Fields kept in the per-server JSON blob (passed through to D1).
# Anything the detail page renders must be in here. Order doesn't matter.
DETAIL_FIELDS = [
    "owner",
    "name",
    "repo_url",
    "description",
    "stars",
    "forks",
    "runtime",
    "sources",
    "is_mcp_server",
    "mcp_confidence",
    "mcp_category",
    "mcp_tags",
    "primary_function",
    "requires_api_key",
    "recommended_score",
    "llm_verified_at",
    # Optional date columns — included if present in the source row.
    "pushed_at",
    "github_pushed_at",
    "updated_at",
    "github_updated_at",
    "last_commit_at",
]

BATCH = 50  # rows per multi-row INSERT (D1 caps statements ~100KB)


def sql_quote(v) -> str:
    """SQLite string literal escape: wrap in '' and double any internal quote."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v).replace("'", "''")
    return f"'{s}'"


def main() -> None:
    if not SERVERS_JSON.exists():
        raise SystemExit(
            f"FATAL: {SERVERS_JSON} not found. Run `npm run export-data` first."
        )

    print(f"Reading {SERVERS_JSON.name}…")
    with open(SERVERS_JSON, "r") as f:
        servers = json.load(f)
    print(f"  Loaded {len(servers):,} servers.")

    print(f"Writing {OUT_SQL.name}…")
    with open(OUT_SQL, "w") as out:
        out.write("-- Generated by scripts/export_d1_sql.py. Do not edit.\n")
        out.write("DROP TABLE IF EXISTS servers;\n")
        out.write(
            """CREATE TABLE servers (
  owner TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT,
  score INTEGER,
  data TEXT NOT NULL,
  PRIMARY KEY (owner, name)
);
"""
        )
        out.write("CREATE INDEX idx_category_score ON servers(category, score DESC);\n\n")

        # Write batched INSERTs
        for i in range(0, len(servers), BATCH):
            chunk = servers[i : i + BATCH]
            out.write("INSERT INTO servers (owner, name, category, score, data) VALUES\n")
            lines = []
            for s in chunk:
                blob = {k: s.get(k) for k in DETAIL_FIELDS if k in s}
                data = json.dumps(blob, separators=(",", ":"))
                cat = s.get("mcp_category") or "unknown"
                score = int(s.get("recommended_score") or 0)
                lines.append(
                    f"  ({sql_quote(s['owner'])}, {sql_quote(s['name'])}, "
                    f"{sql_quote(cat)}, {score}, {sql_quote(data)})"
                )
            out.write(",\n".join(lines))
            out.write(";\n")

    size_mb = OUT_SQL.stat().st_size / 1024 / 1024
    print(f"  Wrote {OUT_SQL.name}: {size_mb:.1f} MB")
    print(f"  Statements: 1 DROP + 1 CREATE TABLE + 1 CREATE INDEX + "
          f"{(len(servers) + BATCH - 1) // BATCH} INSERTs")
    print()
    print("Next: `npm run upload-d1` (requires wrangler installed and logged in).")


if __name__ == "__main__":
    main()
